php5-apache:
  image: php5-apache:latest
  container_name: php5-apache
  hostname: docker-php5
  ports:
    - "9980:80"
  volumes:
    - "/vagrant:/vagrant"
  tty: true
  stdin_open: true
  environment:
    COLUMNS: 237 # 何故か幅が狭いため